name: 'build ghost-core (x86_64-linux-gnu)'

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [x86_64-linux-gnu]

    steps:
      - uses: actions/checkout@v2

      - name: Cache apt depencenies
        uses: actions/cache@v2
        id: cache-apt
        with:
          path: "~/apt-cache"
          key: apt-cache

      - name: Cache depends
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: depends/${{ matrix.os }}
          key: ${{ matrix.os }}-${{ hashFiles('depends/packages/*.mk') }}

      - name: Install dependencies
        env:
          CACHE_HIT: ${{steps.cache-apt.outputs.cache-hit}}
          DEPS: build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/apt-cache/* /
          else
            sudo apt-get update && sudo apt-get install -yq $DEPS
            mkdir -p ~/apt-cache
            for dep in $DEPS; do
                dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/apt-cache/
            done
          fi

      - name: Build depends
        if: steps.cache-dependencies.outputs.cache-hit != 'true' && steps.cache-apt.outputs.cache-hit != 'true'
        run: cd depends/ && make -j4 HOST=${{matrix.os}} NO_USB=1

      - name: Refresh automake configs
        run: ./autogen.sh

      - name: Configure automake
        run: ./configure --prefix=`pwd`/depends/${{ matrix.os }} --with-gui=qt5

      - name: Build codebase
        run: make -j4

      - name: Unittests
        run: make check

  build-macos:
    runs-on: macOS-latest
    env:
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-build-
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install automake libtool boost miniupnpc pkg-config python qt libevent qrencode protobuf hidapi librsvg sqlite berkeley-db4
  
      - name: Refresh automake configs
        run: ./autogen.sh

      - name: Configure automake
        run: ./configure --prefix=`pwd`/depends/${{ runner.os }} --with-gui=auto

      - name: Build codebase
        run: make -j4
        
      - name: Unittests
        run: make check

      - name: Deploy
        run: make deploy


